# Default values for geocentapp.
# Declare variables to be passed into your templates.

counter:
  replicaCount: 1
  image:
    repository: pchen2145/geocent-countersvc
    tag: v1 
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 5000 
    targetPort: 5000
 
person:
  replicaCount: 1
  image:
    repository: pchen2145/geocent-personsvc 
    tag: v1
    pullPolicy: Always 

  service:
    type: ClusterIP
    port: 8080 
    targetPort: 8080

nginx:
  replicaCount: 1
  image:
    repository: pchen2145/geocent-nginx 
    tag: v1
    pullPolicy: Always 

  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30500
    protocol: TCP

webapp:
  replicaCount: 1
  image:
    repository: pchen2145/geocent-webapp 
    tag: v1
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

configMap:
  postgres:
    host: postgres
    user:  postgres
    password: postgres
    port: 5432
  
  redis:
    host: redis
    port: 6379
