apiVersion: v1
kind: Service
metadata:
  name: counter-service 
  labels:
    app: counter-service
spec:
  type: {{ .Values.counter.service.type }}
  ports:
    - port: {{ .Values.counter.service.port }}
      targetPort: {{ .Values.counter.service.targetPort }} 
      protocol: TCP
  selector:
    app: counter
