apiVersion: v1
kind: Service
metadata:
  name: person-service
  labels:
    app: person-service
spec:
  type: {{ .Values.person.service.type }}
  ports:
    - port: {{ .Values.person.service.port }}
      targetPort: {{ .Values.person.service.targetPort }} 
      protocol: TCP
  selector:
    app: person
