# Default values for geocentapp.
# Declare variables to be passed into your templates.

redis:
  replicaCount: 1
  image:
    repository: pchen2145/geocent-redis 
    tag: v1
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379